/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_so;

/**
 *
 * @author Cjavi
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() 
    {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFilosofoA3 = new javax.swing.JLabel();
        lblFilosofo = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblFilosofoA = new javax.swing.JLabel();
        lblFilosofoB = new javax.swing.JLabel();
        lblFilosofoC = new javax.swing.JLabel();
        lblFilosofoD = new javax.swing.JLabel();
        lblFilosofoE = new javax.swing.JLabel();
        lblEstadoA = new javax.swing.JLabel();
        lblEstadoB = new javax.swing.JLabel();
        lblEstadoC = new javax.swing.JLabel();
        lblEstadoD = new javax.swing.JLabel();
        lblEstadoE = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();

        lblFilosofoA3.setText("Filosofo A");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFilosofo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        lblFilosofo.setText("Filosofo");

        lblEstado.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        lblEstado.setText("Estado");

        lblFilosofoA.setText("Filosofo A");

        lblFilosofoB.setText("Filosofo B");

        lblFilosofoC.setText("Filosofo C");

        lblFilosofoD.setText("Filosofo D");

        lblFilosofoE.setText("Filosofo E");

        lblEstadoA.setText("--------");

        lblEstadoB.setText("--------");

        lblEstadoC.setText("--------");

        lblEstadoD.setText("--------");

        lblEstadoE.setText("--------");

        btnIniciar.setText("Iniciar Almuerzo");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFilosofo)
                            .addComponent(lblFilosofoA)
                            .addComponent(lblFilosofoB))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFilosofoE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFilosofoD)
                                .addComponent(lblFilosofoC)))
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoC)
                    .addComponent(lblEstadoB)
                    .addComponent(lblEstadoA)
                    .addComponent(lblEstado)
                    .addComponent(lblEstadoD)
                    .addComponent(lblEstadoE))
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIniciar)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilosofo)
                    .addComponent(lblEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilosofoA)
                    .addComponent(lblEstadoA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilosofoB)
                    .addComponent(lblEstadoB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilosofoC)
                    .addComponent(lblEstadoC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilosofoD)
                    .addComponent(lblEstadoD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilosofoE)
                    .addComponent(lblEstadoE))
                .addGap(18, 18, 18)
                .addComponent(btnIniciar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
      
      
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoA;
    private javax.swing.JLabel lblEstadoB;
    private javax.swing.JLabel lblEstadoC;
    private javax.swing.JLabel lblEstadoD;
    private javax.swing.JLabel lblEstadoE;
    private javax.swing.JLabel lblFilosofo;
    private javax.swing.JLabel lblFilosofoA;
    private javax.swing.JLabel lblFilosofoA3;
    private javax.swing.JLabel lblFilosofoB;
    private javax.swing.JLabel lblFilosofoC;
    private javax.swing.JLabel lblFilosofoD;
    private javax.swing.JLabel lblFilosofoE;
    // End of variables declaration//GEN-END:variables
}
